(function(g){var window=this;var zCa=function(a,b){return g.Sb(a,b)},i6=function(a){g.Nm(a,"zx",g.vb());
return a},j6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Qm(a.o,b,c)},ACa=function(a,b){var c=[];
g.Ck(b,function(a){try{var b=g.lD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.kD(b)&&c.push(a):c.push(a)},a);
return c},BCa=function(a,b){var c=ACa(a,b);
(0,g.D)(c,function(a){g.lD.prototype.remove.call(this,a)},a)},CCa=function(a){if(a.Id){if(a.Id.locationOverrideToken)return{locationOverrideToken:a.Id.locationOverrideToken};
if(null!=a.Id.latitudeE7&&null!=a.Id.longitudeE7)return{latitudeE7:a.Id.latitudeE7,longitudeE7:a.Id.longitudeE7}}return null},DCa=function(a,b,c,d){var e=new g.Em(null,void 0);
a&&g.Fm(e,a);b&&g.Gm(e,b);c&&g.Hm(e,c);d&&g.Im(e,d);return e},ECa=function(a){g.RF[a]&&(a=g.RF[a],(0,g.D)(a,function(a){g.PF[a]&&delete g.PF[a]}),a.length=0)},FCa=function(a){var b=g.OF();
if(b)if(b.clear(a),a)ECa(a);else for(var c in g.RF)ECa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.ym;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",GCa(this,a.capabilities||""),HCa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},GCa=function(a,b){a.capabilities.clear();
(0,g.Td)(b.split(","),g.Da(zCa,ICa)).forEach(function(b){a.capabilities.add(b)})},HCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},JCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},KCa=function(a){return new l6(a)},LCa=function(a){return g.xa(a)?(0,g.I)(a,KCa):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.xa(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},MCa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.Ia(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.Ia(a,function(a){return m6(a,b)})},NCa=function(){var a=(0,g.PG)();
a&&BCa(a,a.o.ee(!0))},s6=function(){var a=g.SG("yt-remote-connected-devices")||[];
g.db(a);return a},OCa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},PCa=function(a){g.RG("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.SG("yt-remote-device-id");a||(a=p6(),g.RG("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Ma(a,b);g.UG()&&g.fb(a,b);a=OCa(a);if(g.Na(a))try{g.zG("remote_sid")}catch(c){}else try{g.yG("remote_sid",a.join(","),-1)}catch(c){}},QCa=function(){return g.SG("yt-remote-session-browser-channel")},RCa=function(){return g.SG("yt-remote-local-screens")||[]},SCa=function(){g.RG("yt-remote-lounge-token-expiration",!0,86400)},TCa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(RCa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.mm)(c,function(a){return!g.Ma(b,a)})&&SCa();
g.RG("yt-remote-local-screens",a,31536E3)},UCa=function(a,b){g.RG("yt-remote-session-browser-channel",a);
g.RG("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Ma(c,d)||c.push(d);PCa(c);v6()},w6=function(a){a||(g.TG("yt-remote-session-screen-id"),g.TG("yt-remote-session-video-id"));
v6();a=s6();g.Ra(a,u6());PCa(a)},VCa=function(){if(!x6){var a=g.wD();
a&&(x6=new g.fD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},WCa=function(){var a=window.document.createElement("a");
g.gd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},XCa=function(a,b,c){c=void 0===c?null:c;
var d=g.Md("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.id(d,g.ke("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},YCa=function(a){a=void 0===a?null:a;
var b=WCa(),c=window.document.getElementById(b),d=c&&g.ZE(c,"loaded");d||c&&!d||(c=XCa(b,function(){g.ZE(c,"loaded")||(g.YE(c,"loaded","true"),g.VF(b),g.XD(g.Da(FCa,b),0))},a))},ZCa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):YCa(a)},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},$Ca=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?aDa(a.shift(),function(){z6(a)}):A6()},bDa=function(a){return"chrome-extension://"+a+B6},aDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=$Ca();
a&&a(!1,"No cast extension found")},D6=function(){if(cDa){var a=2,b=$Ca(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;aDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},dDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},eDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Bd=b;this.D=(0,g.B)(this.qL,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.Um(this);this.A=new g.zg;this.A.setInterval(250)},gDa=function(a,b,c){a.tk=1;
a.Ph=i6(b.clone());a.yj=c;a.D=!0;fDa(a,null)},H6=function(a,b,c,d,e){a.tk=1;
a.Ph=i6(b.clone());a.yj=null;a.D=c;e&&(a.AF=!1);fDa(a,d)},fDa=function(a,b){a.ol=(0,g.H)();
I6(a);a.ti=a.Ph.clone();j6(a.ti,"t",a.F);a.Vn=0;a.Uc=a.o.qt(a.o.Mn()?b:null);0<a.Zt&&(a.Sq=new g.dl((0,g.B)(a.QG,a,a.Uc),a.Zt));a.Z.W(a.Uc,"readystatechange",a.GW);var c=a.Zi?g.bc(a.Zi):{};a.yj?(a.Mr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Uc.send(a.ti,a.Mr,a.yj,c)):(a.Mr="GET",a.AF&&!g.Id&&(c.Connection="close"),a.Uc.send(a.ti,a.Mr,null,c));a.o.Hf(1)},jDa=function(a,b,c){for(var d=!0;!a.Mi&&a.Vn<c.length;){var e=hDa(a,c);
if(e==J6){4==b&&(a.Qh=4,K6(15),d=!1);break}else if(e==iDa){a.Qh=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Qh=1,K6(17),d=!1);a.Of=a.Of&&d;d||(M6(a),N6(a))},hDa=function(a,b){var c=a.Vn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return iDa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.Vn=d+c;return e},lDa=function(a,b){a.ol=(0,g.H)();
I6(a);var c=b?window.location.hostname:"";a.ti=a.Ph.clone();g.Nm(a.ti,"DOMAIN",c);g.Nm(a.ti,"t",a.F);try{a.Pf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Qh=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in kDa)k=O6[l]=kDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.jd(g.zc("b/12014412"),d+"</body></html>");a.Pf.open();a.Pf.write(g.$c(c));a.Pf.close();a.Pf.parentWindow.m=(0,g.B)(a.OV,a);a.Pf.parentWindow.d=(0,g.B)(a.IE,a,!0);a.Pf.parentWindow.rpcClose=(0,g.B)(a.IE,a,!1);c=a.Pf.createElement("DIV");a.Pf.parentWindow.document.body.appendChild(c);d=g.Nc(a.ti.toString());d=g.ob(g.Kc(d));d=g.jd(g.zc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,g.$c(d));a.o.Hf(1)},
I6=function(a){a.Gx=(0,g.H)()+a.C;
mDa(a,a.C)},mDa=function(a,b){if(null!=a.Fl)throw Error("WatchDog timer not null");
a.Fl=P6((0,g.B)(a.eW,a),b)},Q6=function(a){a.Fl&&(g.x.clearTimeout(a.Fl),a.Fl=null)},N6=function(a){a.o.MA()||a.Mi||a.o.Cq(a)},M6=function(a){Q6(a);
g.kf(a.Sq);a.Sq=null;a.A.stop();g.$m(a.Z);if(a.Uc){var b=a.Uc;a.Uc=null;b.abort();b.dispose()}a.Pf&&(a.Pf=null)},L6=function(a,b){try{a.o.AE(a,b),a.o.Hf(4)}catch(c){}},oDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;nDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){oDa(a,b,c,d,f)},f)})}},nDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},pDa=function(a){this.o=a;
this.A=new F6},qDa=function(a){var b=S6(a.o,a.Ql,"/mail/images/cleardot.gif");
i6(b);oDa(b.toString(),5E3,(0,g.B)(a.vK,a),3,2E3);a.Hf(1)},U6=function(a){var b=a.o.J;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Ge=new G6(a,void 0,void 0,void 0),a.Ge.Zi=a.Xt,b=a.o,b=S6(b,b.Mn()?a.Fm:null,a.Yt),K6(5),!g.Gd||g.rc(10))j6(b,"TYPE","xmlhttp"),H6(a.Ge,b,!1,a.Fm,!1);else{j6(b,"TYPE","html");var c=a.Ge;a=!!a.Fm;c.tk=3;c.Ph=i6(b.clone());lDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},rDa=function(a,b){this.o=a;
this.map=b;this.context=null},sDa=function(a){g.mf.call(this,"statevent",a)},tDa=function(a,b){g.mf.call(this,"timingevent",a);
this.size=b},uDa=function(a){g.mf.call(this,"serverreachability",a)},xDa=function(a){vDa(a);
if(3==a.o){var b=a.wn++,c=a.kp.clone();g.Nm(c,"SID",a.B);g.Nm(c,"RID",b);g.Nm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.tk=2;b.Ph=i6(c.clone());(new window.Image).src=b.Ph;b.ol=(0,g.H)();I6(b)}wDa(a)},yDa=function(a){a.RK(1,0);
a.kp=S6(a,null,a.Wt);X6(a)},vDa=function(a){a.Ch&&(a.Ch.abort(),a.Ch=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Hg&&(g.x.clearTimeout(a.Hg),a.Hg=null);Y6(a);a.je&&(a.je.cancel(),a.je=null);a.Hh&&(g.x.clearTimeout(a.Hh),a.Hh=null)},zDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new rDa(a.AR++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.je||a.Hh||(a.Hh=P6((0,g.B)(a.GE,a),0),a.hk=0)},BDa=function(a,b){if(1==a.o){if(!b){a.wn=Math.floor(1E5*Math.random());
var c=a.wn++,d=new G6(a,"",c,void 0);d.Zi=null;var e=Z6(a),f=a.kp.clone();g.Nm(f,"RID",c);g.Nm(f,"CVER","1");W6(a,f);gDa(d,f,e);a.je=d;a.o=2}}else 3==a.o&&(b?ADa(a,b):0==a.A.length||a.je||ADa(a))},ADa=function(a,b){if(b)if(6<a.Oi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.wn-1;var d=Z6(a)}else c=b.G,d=b.yj;else c=a.wn++,d=Z6(a);var e=a.kp.clone();g.Nm(e,"SID",a.B);g.Nm(e,"RID",c);g.Nm(e,"AID",a.Ik);W6(a,e);c=new G6(a,a.B,c,a.hk+1);c.Zi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.je=c;gDa(c,e,d)},W6=function(a,b){if(a.Ad){var c=a.Ad.tA();
c&&g.Hb(c,function(a,c){g.Nm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Oi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Oi?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},CDa=function(a){a.Ac||a.Hg||(a.G=1,a.Hg=P6((0,g.B)(a.FE,a),0),a.Vj=0)},$6=function(a){if(a.Ac||a.Hg||3<=a.Vj)return!1;
a.G++;a.Hg=P6((0,g.B)(a.FE,a),DDa(a,a.Vj));a.Vj++;return!0},T6=function(a,b,c){a.Kr=c;
a.gg=b.Vg;a.F||yDa(a)},Y6=function(a){null!=a.Pi&&(g.x.clearTimeout(a.Pi),a.Pi=null)},DDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Ad&&(c=null);var d=(0,g.B)(a.uX,a);c||(c=new g.Em("//www.google.com/images/cleardot.gif"),i6(c));nDa(c.toString(),1E4,d)}else K6(2);EDa(a,b)},EDa=function(a,b){a.o=0;
a.Ad&&a.Ad.vz(b);wDa(a);vDa(a)},wDa=function(a){a.o=0;
a.gg=-1;if(a.Ad)if(0==a.C.length&&0==a.A.length)a.Ad.Ts();else{g.Va(a.C);var b=g.Va(a.A);a.C.length=0;a.A.length=0;a.Ad.Ts(b)}},S6=function(a,b,c){var d=g.Om(c);
if(""!=d.A)b&&g.Gm(d,b+"."+d.A),g.Hm(d,d.D);else{var e=window.location;d=DCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.km&&g.Hb(a.km,function(a,b){g.Nm(d,b,a)});
g.Nm(d,"VER",a.Oi);W6(a,d);return d},P6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new sDa(b7,a))},FDa=function(){},GDa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.iu(this.FV,0,this);g.N(this,this.o);this.Bd=5E3;this.A=0;if(g.za(a))b&&(a=(0,g.B)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.eD;this.A=new c7(this.eY,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},HDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Kr,sessionId:a.o.B,arrayId:a.o.Ik}},IDa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&BDa(a.o),xDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},JDa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Og(a)||"";b&&(this.port=":"+b);this.domain=g.Ng(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Xg(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Da(a.C,d,!0),onError:g.Da(a.B,e),Fd:g.Da(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.nE(b,a)},NDa=function(){var a=KDa;
LDa();i7.push(a);MDa(i7)},j7=function(a,b){LDa();
var c=i7,d=ODa(a,String(b));g.Na(c)?PDa(d):(MDa(c),(0,g.D)(c,function(a){a(d)}))},LDa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},PDa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},MDa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},ODa=function(a,b){var c=((0,g.H)()-QDa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.GF.call(this);
this.G=a;this.o=[]},RDa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},SDa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Td)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=RDa(a,b[d])||c;return c},TDa=function(a,b){var c=a.o.length;
a.o=(0,g.Td)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.GF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},UDa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.DL,a),(0,g.B)(a.CL,a))}},p7=function(a){var b=LCa(RCa());
b=(0,g.Td)(b,function(a){return!a.uuid});
return SDa(a,b)},r7=function(a,b){TCa((0,g.I)(a.o,JCa));
b&&SCa()},t7=function(a,b){g.GF.call(this);
this.F=b;var c=g.SG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Fg(this.o))},VDa=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Lb(b)!=g.Lb(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Fg(a.o)),a.o=b,a.V("screenChange"));WDa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.ZD(a.B);
a.B=g.XD((0,g.B)(a.Kw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},XDa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},WDa=function(a){a=g.Pb(g.Ib(a.o,function(a){return a}));
g.db(a);a.length?g.RG("yt-remote-online-screen-ids",a.join(","),60):g.TG("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};YDa(this)},$Da=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ae();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);VDa(a.A,l,function(a){e(a?l:null)})}else c?ZDa(a,c,(0,g.B)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));VDa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},aEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},ZDa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.nE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},bEa=function(a){a.o=a.B.Ae();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},YDa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.SL,a));bEa(a);a.C=LCa(g.SG("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.B)(a.Ae,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.RG("yt-remote-automatic-screen-cache",(0,g.I)(a.C,JCa)));y7(a);a.D[b.uuid]=b.id;g.RG("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.SG("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.GF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},A7=function(a,b){j7(a.N,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.kY,this);this.D=(0,g.B)(this.qW,this);this.C=g.XD((0,g.B)(function(){cEa(this,null)},this),12E4)},dEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Fg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.B)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Fg(b))},cEa=function(a,b){g.ZD(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Dq,a),d=(0,g.B)(a.Fe,a);a.CA(b,c,d,5)}}else a.Fe(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.B)(this.nY,this);this.o=g.z},eEa=function(a){a.o=a.J.YG(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.z;
this.Dq(a)},a),(0,g.B)(function(a){this.o=g.z;
this.Fe(a)},a))},fEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}VCa()&&(b.env_useStageMdx=1);return g.Vg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.XD((0,g.B)(this.Kk,this,null),150)},E7=function(a,b,c,d){g.GF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.RU,this)},gEa=function(a,b){return b?g.Ia(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},KDa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.kf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.DE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Kk(null)):a.V("yt-remote-cast2-session-change",null))},hEa=function(a){var b=a.A.XG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=gEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},nEa=function(a,b,c,d,e,f,k){iEa()?jEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?kEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?kEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.TG("yt-remote-cast-available"),g.TG("yt-remote-cast-receiver"),lEa(),
c(!1))},d?ZCa():C6("CriOS")?dDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?eDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(mEa.map(bDa))):A6())):I7("Cannot initialize because not running Chrome")},lEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);oEa(!1);g.TF(N7);N7.length=0},O7=function(){return!!g.SG("yt-remote-cast-installed")},pEa=function(){var a=g.SG("yt-remote-cast-receiver");
return a?a.friendlyName:null},qEa=function(){I7("clearCurrentReceiver");
g.TG("yt-remote-cast-receiver")},rEa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.SF("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},iEa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.iI||a},sEa=function(a,b){M7().init(a,b)},jEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.RG("yt-remote-cast-available",a);g.WF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.RG("yt-remote-cast-receiver",a);g.WF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.RG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.TG("yt-remote-cast-receiver");g.WF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},kEa=function(a,b){L7(!0);
J7(!1);sEa(a,function(a){a?(oEa(!0),g.VF("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.TG("yt-remote-cast-available"),g.TG("yt-remote-cast-receiver"),lEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.RG("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},oEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.kg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.kg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.rb()?((0,g.H)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.H)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.A);b.hasPrevious=a.kg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.GF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.uC;this.B=this.A=null;this.J=(0,g.B)(this.kS,this);this.G=(0,g.B)(this.zn,this);this.H=(0,g.B)(this.jS,this);this.K=(0,g.B)(this.wS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Nx,this),tEa(this))):c=3;0!=c&&(b?this.Nx(c):g.XD((0,g.B)(function(){this.Nx(c)},this),0));
var d=rEa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},tEa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Da(this.MU,a),this))},a)},uEa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.Bc()&&g.wC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){uEa(a);
a.C.setPlayerContextData(Y7(b));tEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.zn(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.zn(a.B.media[0]))},vEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.B)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.GF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.N=window.NaN;this.Y=[];this.C=this.G=this.B=this.jb=this.o=null;this.sa=a;this.Y.push(g.pF(window,"beforeunload",(0,g.B)(this.uL,this)));this.A=[];this.jb=new S7;this.ca=b.id;this.o=wEa(this,c);this.o.subscribe("handlerOpened",this.oS,this);this.o.subscribe("handlerClosed",this.lS,this);this.o.subscribe("handlerError",this.mS,this);this.o.subscribe("handlerMessage",this.nS,this);JDa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.UG()&&g.RG("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},wEa=function(a,b){return new d7(g7(a.sa,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},xEa=function(a){a.D=g.XD((0,g.B)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.ZD(a.D);
a.D=window.NaN},k8=function(a){g.ZD(a.N);
a.N=window.NaN},yEa=function(a){l8(a);
a.L=g.XD((0,g.B)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.ZD(a.L);
a.L=window.NaN},AEa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.aa()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),zEa(a)):a.F(1)},BEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Vb(b.params)?a.jb.A=null:a.jb.A=b.params,a.V("remotePlayerChange"))},CEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.V("remoteQueueChange")},EEa=function(a,b){b.params=b.params||{};
CEa(a,b);DEa(a,b);a.V("autoplayDismissed")},DEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.o&&(c=-1E3);a.jb.o=c;c=Number(b.params.loadedTime);a.jb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.J=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.jb.o?yEa(a):l8(a);
a.V("remotePlayerChange")},FEa=function(a,b){if(-1E3!=a.jb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},GEa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},HEa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},IEa=function(a,b){var c="true"==b.params.hasNext;
a.jb.kg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},zEa=function(a){g.ZD(a.K);
a.K=g.XD((0,g.B)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Fg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.hd=a;this.A=[];this.A.push(this.hd.$_s("screenChange",(0,g.B)(this.iY,this)));this.A.push(this.hd.$_s("onlineScreenChange",(0,g.B)(this.lU,this)))},NEa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.RD("MDX_CONFIG")||b;NCa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),VCa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));JEa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);nEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.WF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Fg(b)),t8.push(g.SF("yt-remote-cast2-availability-change",function(){g.WF("yt-remote-receiver-availability-change")})),t8.push(g.SF("yt-remote-cast2-receiver-selected",function(){u8(null);
g.WF("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.SF("yt-remote-cast2-receiver-resumed",function(){g.WF("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.SF("yt-remote-cast2-session-change",KEa)),t8.push(g.SF("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),qEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.MF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Fg(a)),LEa(a),c.start(),r8()||MEa())},PEa=function(){var a=OEa();
O7()&&g.SG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},OEa=function(){var a=q8().hd.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return MCa(a)},z8=function(){var a=QEa();
!a&&O7()&&pEa()&&(a={key:"cast-selector-receiver",name:pEa()});return a},QEa=function(){var a=OEa(),b=x8();
b||(b=v8());return g.Ia(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Ae();return r6(b,a)},KEa=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},REa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},SEa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||REa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.D)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.WF("yt-remote-connection-change",!1):!b&&a&&g.WF("yt-remote-connection-change",!0)},v8=function(){var a=g.UG();
if(!a)return null;var b=q8().Ae();return r6(b,a)},B8=function(a,b){x8()&&x8();
REa(a.id);var c=new g8(o8,a,w8());c.connect(b,SEa());c.subscribe("beforeDisconnect",function(a){g.WF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},MEa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),qEa(),s8("Skipping connecting because no session screen found."))},JEa=function(){var a=w8();
if(g.Vb(a)){a=u6();var b=g.SG("yt-remote-session-name")||"",c=g.SG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},LEa=function(a){a?(g.RG("yt-remote-session-app",a.app),g.RG("yt-remote-session-name",a.name)):(g.TG("yt-remote-session-app"),g.TG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.G=a;this.T=b;this.A=new g.DF(this);g.N(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.DT);this.A.R(b,"captionschanged",this.iS);this.A.R(b,"captionssettingschanged",this.jG);this.A.R(b,"videoplayerreset",this.Eq);this.A.R(b,"mdxautoplaycancel",this.uK);this.O=this.A.R(b,"onVolumeChange",this.kE);this.F=!1;this.o=c;c.subscribe("proxyStateChange",this.zE,this);c.subscribe("remotePlayerChange",this.Cn,this);c.subscribe("remoteQueueChange",this.Eq,this);c.subscribe("autoplayUpNext",this.VD,
this);c.subscribe("previousNextChange",this.wE,this);c.subscribe("nowAutoplaying",this.nE,this);c.subscribe("autoplayDismissed",this.UD,this);this.suggestion=null;this.H=new g.CP(64);this.B=new g.iu(this.fG,500,this);g.N(this,this.B);this.C=new g.iu(this.gG,1E3,this);g.N(this,this.C);this.K=new E6(this.JX,0,this);g.N(this,this.K);this.D={};this.L=new g.iu(this.FG,1E3,this);g.N(this,this.L);this.J=new g.dl(this.mQ,1E3,this);g.N(this,this.J);this.N=g.z;this.jG();this.Eq();this.Cn()},G8=function(a,b){var c=
a.G,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},TEa=function(a){G8(a,0);
a.B.stop();H8(a,new g.CP(64))},J8=function(a,b){if(I8(a)&&!a.F){var c=null;
b&&(c={style:a.T.rj()},g.ec(c,b));a.o.UF(a.T.getVideoData(1).videoId,c);a.D=a8(a.o).A}},K8=function(a,b){var c=a.T.sg();
if(c){var d=c.ye();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Ck;f=CCa(f);var n=a8(c);l=l||0;var q={videoId:k,currentIndex:l};X7(n,k,l);g.u(b)&&(V7(n,b),q.currentTime=b);g.u(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Fg(f));e8(c,"setPlaylist",q);e||c8(c,n);H8(a,new g.CP(1))},UEa=function(a,b){if(b){var c=a.T.Ec("captions","tracklist",{vB:1});
c&&c.length?(a.T.Ud("captions","track",b),a.F=!1):(a.T.Sk("captions"),a.F=!0)}else a.T.Ud("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.T.getVideoData(1).videoId},H8=function(a,b){a.C.stop();
var c=a.H;if(!g.HP(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.eU(a.T,d);a.H=b;VEa(a.G,c,b)}},L8=function(a){g.V.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.kqa()]},{I:"div",M:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.eV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);WEa(this,g.aU(a))},WEa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Ec("remote","currentReceiver").name};
c=g.W(b,128)?g.GX("Error on $RECEIVER_NAME",c):b.rb()||g.W(b,4)?g.GX("Playing on $RECEIVER_NAME",c):g.GX("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.CY.call(this,"Play on",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},N8=function(a){g.FU.call(this,a);
this.B={key:p6(),name:"This computer"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.CP(64);this.J=0;if(!g.KM(g.X(this.o))){a=this.o;var b=g.KH(a);b&&(b=b.mn())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.vU(a,b.element,4)}},VEa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.MP(c,b))},O8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)A8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.sg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ck,index:Math.max(a.o.yC(),0),currentTime:0==f?void 0:f};(d=CCa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Fg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||null):
K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.WF("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().Ae(),(d=r6(d,b.key))&&B8(d,1))}},kDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},XEa={},ICa={xZ:"atp",d4:"ska",t3:"que",F2:"mus",Y3:"sus",H0:"dsp"};
k6.prototype.Oo=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",cDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),mEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(E6,g.M);g.h=E6.prototype;g.h.pL=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Bd:this.Ea=g.Ag(this.D,this.Bd)};
g.h.stop=function(){this.Ea&&(g.Bg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();E6.fa.X.call(this)};
g.h.qL=function(){this.B?(this.Ea=g.Ag(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.Zi=null;g.h.Of=!1;g.h.Fl=null;g.h.Gx=null;g.h.ol=null;g.h.tk=null;g.h.Ph=null;g.h.ti=null;g.h.yj=null;g.h.Uc=null;g.h.Vn=0;g.h.Pf=null;g.h.Mr=null;g.h.Qh=null;g.h.Gm=-1;g.h.AF=!0;g.h.Mi=!1;g.h.Zt=0;g.h.Sq=null;var iDa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.GW=function(a){a=a.target;var b=this.Sq;b&&3==g.rx(a)?b.Cm():this.QG(a)};
g.h.QG=function(a){try{if(a==this.Uc)a:{var b=g.rx(this.Uc),c=this.Uc.A,d=this.Uc.getStatus();if(g.Gd&&!g.rc(10)||g.Id&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.of&&!g.vx(this.Uc))break a;this.Mi||4!=b||7==c||(8==c||0>=d?this.o.Hf(3):this.o.Hf(2));Q6(this);var e=this.Uc.getStatus();this.Gm=e;var f=g.vx(this.Uc);(this.Of=200==e)?(4==b&&M6(this),this.D?(jDa(this,b,f),g.of&&this.Of&&3==b&&(this.Z.W(this.A,"tick",this.BW),this.A.start())):L6(this,f),this.Of&&!this.Mi&&(4==b?this.o.Cq(this):
(this.Of=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Qh=3,K6(13)):(this.Qh=0,K6(14)),M6(this),N6(this))}}catch(k){this.Uc&&g.vx(this.Uc)}finally{}};
g.h.BW=function(){var a=g.rx(this.Uc),b=g.vx(this.Uc);this.Vn<b.length&&(Q6(this),jDa(this,a,b),this.Of&&4!=a&&I6(this))};
g.h.OV=function(a){P6((0,g.B)(this.NV,this,a),0)};
g.h.NV=function(a){this.Mi||(Q6(this),L6(this,a),I6(this))};
g.h.IE=function(a){P6((0,g.B)(this.MV,this,a),0)};
g.h.MV=function(a){this.Mi||(M6(this),this.Of=a,this.o.Cq(this),this.o.Hf(4))};
g.h.cancel=function(){this.Mi=!0;M6(this)};
g.h.eW=function(){this.Fl=null;var a=(0,g.H)();0<=a-this.Gx?(2!=this.tk&&this.o.Hf(3),M6(this),this.Qh=2,K6(18),N6(this)):mDa(this,this.Gx-a)};g.h=pDa.prototype;g.h.Xt=null;g.h.Ge=null;g.h.Tq=!1;g.h.NA=null;g.h.gp=null;g.h.Ru=null;g.h.Yt=null;g.h.Ze=null;g.h.Vg=-1;g.h.Fm=null;g.h.Ql=null;g.h.connect=function(a){this.Yt=a;a=S6(this.o,null,this.Yt);K6(3);this.NA=(0,g.H)();var b=this.o.H;null!=b?(this.Fm=b[0],(this.Ql=b[1])?(this.Ze=1,qDa(this)):(this.Ze=2,U6(this))):(j6(a,"MODE","init"),this.Ge=new G6(this,void 0,void 0,void 0),this.Ge.Zi=this.Xt,H6(this.Ge,a,!1,null,!0),this.Ze=0)};
g.h.vK=function(a){if(a)this.Ze=2,U6(this);else{K6(4);var b=this.o;b.gg=b.Ch.Vg;a7(b,9)}a&&this.Hf(2)};
g.h.qt=function(a){return this.o.qt(a)};
g.h.abort=function(){this.Ge&&(this.Ge.cancel(),this.Ge=null);this.Vg=-1};
g.h.MA=function(){return!1};
g.h.AE=function(a,b){this.Vg=a.Gm;if(0==this.Ze)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.gg=this.Vg;a7(c,2);return}this.Fm=c[0];this.Ql=c[1]}else c=this.o,c.gg=this.Vg,a7(c,2);else if(2==this.Ze)if(this.Tq)K6(7),this.Ru=(0,g.H)();else if("11111"==b){if(K6(6),this.Tq=!0,this.gp=(0,g.H)(),c=this.gp-this.NA,!g.Gd||g.rc(10)||500>c)this.Vg=200,this.Ge.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.gp=this.Ru=(0,g.H)(),this.Tq=!1};
g.h.Cq=function(){this.Vg=this.Ge.Gm;if(this.Ge.Of)0==this.Ze?this.Ql?(this.Ze=1,qDa(this)):(this.Ze=2,U6(this)):2==this.Ze&&((!g.Gd||g.rc(10)?!this.Tq:200>this.Ru-this.gp)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.Ze?K6(9):2==this.Ze&&K6(10);var a=this.o;a.gg=this.Vg;a7(a,2)}};
g.h.Mn=function(){return this.o.Mn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Hf=function(a){this.o.Hf(a)};g.h=V6.prototype;g.h.km=null;g.h.je=null;g.h.Ac=null;g.h.Wt=null;g.h.kp=null;g.h.kz=null;g.h.zp=null;g.h.wn=0;g.h.AR=0;g.h.Ad=null;g.h.Hh=null;g.h.Hg=null;g.h.Pi=null;g.h.Ch=null;g.h.Kr=null;g.h.Ik=-1;g.h.LB=-1;g.h.gg=-1;g.h.hk=0;g.h.Vj=0;g.h.Oi=8;var b7=new g.Nf;g.C(sDa,g.mf);g.C(tDa,g.mf);g.C(uDa,g.mf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.Wt=b;this.km=c||{};d&&g.u(e)&&(this.km.OSID=d,this.km.OAID=e);this.F?(P6((0,g.B)(this.Gz,this,a),100),yDa(this)):this.Gz(a)};
g.h.Gz=function(a){this.Ch=new pDa(this);this.Ch.Xt=null;this.Ch.A=this.D;this.Ch.connect(a)};
g.h.MA=function(){return 0==this.o};
g.h.GE=function(a){this.Hh=null;BDa(this,a)};
g.h.FE=function(){this.Hg=null;this.Ac=new G6(this,this.B,"rpc",this.G);this.Ac.Zi=null;this.Ac.Zt=0;var a=this.kz.clone();g.Nm(a,"RID","rpc");g.Nm(a,"SID",this.B);g.Nm(a,"CI",this.Kr?"0":"1");g.Nm(a,"AID",this.Ik);W6(this,a);if(!g.Gd||g.rc(10))g.Nm(a,"TYPE","xmlhttp"),H6(this.Ac,a,!0,this.zp,!1);else{g.Nm(a,"TYPE","html");var b=this.Ac,c=!!this.zp;b.tk=3;b.Ph=i6(a.clone());lDa(b,c)}};
g.h.AE=function(a,b){if(0!=this.o&&(this.Ac==a||this.je==a))if(this.gg=a.Gm,this.je==a&&3==this.o)if(7<this.Oi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.Hg){if(this.Ac)if(this.Ac.ol+3E3<this.je.ol)Y6(this),this.Ac.cancel(),this.Ac=null;else break a;$6(this);K6(19)}}else this.LB=c[1],0<this.LB-this.Ik&&37500>c[2]&&this.Kr&&0==this.Vj&&!this.Pi&&(this.Pi=P6((0,g.B)(this.dS,this),6E3));else a7(this,11)}else b!=XEa.A_.o&&a7(this,11);else if(this.Ac==a&&
Y6(this),!g.F(b)){c=this.D.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ik=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.zp=e[2],e=e[3],null!=e?this.Oi=e:this.Oi=6,this.o=3,this.Ad&&this.Ad.xz(),this.kz=S6(this,this.Mn()?this.zp:null,this.Wt),CDa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Ad&&this.Ad.wz(e),this.Vj=0)}}};
g.h.dS=function(){null!=this.Pi&&(this.Pi=null,this.Ac.cancel(),this.Ac=null,$6(this),K6(20))};
g.h.Cq=function(a){if(this.Ac==a){Y6(this);this.Ac=null;var b=2}else if(this.je==a)this.je=null,b=1;else return;this.gg=a.Gm;if(0!=this.o)if(a.Of)1==b?(b=(0,g.H)()-a.ol,b7.dispatchEvent(new tDa(b7,a.yj?a.yj.length:0,b,this.hk)),X6(this),this.C.length=0):CDa(this);else{var c=a.Qh,d;if(!(d=3==c||7==c||0==c&&0<this.gg)){if(d=1==b)this.je||this.Hh||1==this.o||2<=this.hk?d=!1:(this.Hh=P6((0,g.B)(this.GE,this,a),DDa(this,this.hk)),this.hk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.RK=function(a){if(!g.Ma(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.uX=function(a){a?K6(2):(K6(1),EDa(this,8))};
g.h.qt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.lx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ad&&this.Ad.isActive(this)};
g.h.Hf=function(a){b7.dispatchEvent(new uDa(b7,a))};
g.h.Mn=function(){return!(!g.Gd||g.rc(10))};
g.h=FDa.prototype;g.h.xz=function(){};
g.h.wz=function(){};
g.h.vz=function(){};
g.h.Ts=function(){};
g.h.tA=function(){return{}};
g.h.isActive=function(){return!0};g.C(c7,g.M);g.h=c7.prototype;g.h.FV=function(){this.Bd=Math.min(3E5,2*this.Bd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Bd+15E3*Math.random();g.ju(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Bd=5E3};g.C(d7,FDa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ae=function(a){return this.B.ae(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.kf(this.B),IDa(this),g.kf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Ad=null);d.Ad=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Ik):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&zDa(this.o,c)};
g.h.xz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)zDa(this.o,a[b])}this.V("handlerOpened")};
g.h.vz=function(a){var b=2==a&&401==this.o.gg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Ts=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.tA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ec(a,this.D);return a};
g.h.wz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),xDa(this.o)):this.V("handlerMessage",new GDa(a[0],a[1]))};
g.h.eY=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.je&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var QDa=(0,g.H)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.C(n7,g.GF);n7.prototype.Ae=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.C(o7,g.GF);var YEa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.WG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.ZD(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();o7.fa.X.call(this)};
g.h.WG=function(){this.Ea=window.NaN;this.o=g.nE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.gY,this),onError:(0,g.B)(this.fY,this),Fd:(0,g.B)(this.hY,this)})};
g.h.gY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.fY=function(a){this.o=null;a.status&&404==a.status?this.A>=YEa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=YEa[this.A],this.Ea=g.XD((0,g.B)(this.WG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.hY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.SG("yt-remote-lounge-token-expiration")&&UDa(this);g.ZD(this.A);this.A=g.XD((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);RDa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||UDa(this)};
g.h.remove=function(a,b){var c=p7(this);TDa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Er=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.ZD(this.A);q7.fa.X.call(this)};
g.h.DL=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.CL=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.C(t7,g.GF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.SG("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?v7(this):(this.C=(0,g.H)()+3E5,g.RG("yt-remote-fast-check-period",this.C),this.Kw())};
g.h.isEmpty=function(){return g.Vb(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Ib(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.X=function(){g.ZD(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.fa.X.call(this)};
g.h.Kw=function(){g.ZD(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=XDa(this);if(g.Lb(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Pb(a).join(",")},(0,g.B)(this.mV,this,a),(0,g.B)(this.lV,this))}else u7(this,{}),v7(this)};
g.h.mV=function(a,b){this.A=null;var c=g.Pb(XDa(this));if(g.eb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.hc("Changing Screen set during request."),this.Kw()};
g.h.lV=function(a){this.hc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.hc=function(a){j7("OnlineScreenService",a)};g.C(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Er=function(a,b,c,d){this.B.contains(a)?this.B.Er(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.Ae=function(a){return a?this.o:g.Ta(this.o,(0,g.Td)(this.C,function(a){return!this.contains(a)},this))};
g.h.XG=function(){return(0,g.Td)(this.Ae(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.YG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.kf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.kf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.jY=function(a,b,c,d){g.nE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new l6(d.screen||{});if(!e.name||aEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);aEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Fd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.kf(this.B);g.kf(this.A);w7.fa.X.call(this)};
g.h.SL=function(){bEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.C(z7,g.GF);g.h=z7.prototype;g.h.Dq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Fe=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.N,a)};
g.h.aH=function(){return null};
g.h.Qw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Qw("");z7.fa.X.call(this)};g.C(B7,z7);g.h=B7.prototype;g.h.Pw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);dEa(this)};
g.h.Kk=function(a){this.info("launchWithParams no-op for Cast: "+g.Fg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Fe()},this),(0,g.B)(function(){this.Fe(Error("Failed to stop receiver app."))},this)):this.Fe(Error("Stopping cast device witout session."))};
g.h.Qw=g.z;g.h.X=function(){this.info("disposeInternal");g.ZD(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.fa.X.call(this)};
g.h.qW=function(a,b){if(!this.la())if(b){var c=g.fx(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Fg(c));switch(d){case "mdxSessionStatus":cEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.CA=function(a,b,c,d){$Da(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.XD((0,g.B)(this.CA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.aH=function(){return this.o};
g.h.kY=function(a){this.la()||a||(A7(this,"Cast session died."),this.Fe())};g.C(C7,z7);g.h=C7.prototype;g.h.Pw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Kk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.ZD(this.F);this.C?this.C.stop((0,g.B)(this.Fe,this,null),(0,g.B)(this.Fe,this,"Failed to stop DIAL device.")):this.Fe()};
g.h.X=function(){this.o();this.o=g.z;g.ZD(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.fa.X.call(this)};
g.h.nY=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.z,this.Fe())};
g.h.Eu=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,fEa(this));a(b);eEa(this)}else this.G=(0,g.B)(function(){g.ZD(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,fEa(this));a(b);eEa(this)},this),this.F=g.XD((0,g.B)(function(){this.G()},this),100)};
g.h.gN=function(a,b,c){$Da(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Dq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Eu(b,c)},this),(0,g.B)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.Eu(b,c)},this))};g.C(D7,z7);D7.prototype.stop=function(){this.Fe()};
D7.prototype.Pw=g.z;D7.prototype.Kk=function(){g.ZD(this.o);this.o=window.NaN;var a=r6(this.J.Ae(),this.A.label);a?this.Dq(a):this.Fe(Error("No such screen"))};
D7.prototype.X=function(){g.ZD(this.o);this.o=window.NaN;D7.fa.X.call(this)};g.C(E7,g.GF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.CE,this),(0,g.B)(this.VU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.NS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),NDa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.ZG,this)),this.B=hEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.hc("Failed to set initial custom receivers: "+g.Fg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.B)(function(a){this.hc("Failed to initialize API: "+g.Fg(a));
b(!1)},this))};
g.h.cX=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.Ae(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=gEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.hc("Failed to set initial custom receivers: "+g.Fg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.Qw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.dX=function(a){this.la()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.Kk(a):this.hc("Setting connection data without a session")};
g.h.mY=function(){this.la()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.CE,this),(0,g.B)(this.qV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.ZG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ra(g.y("yt.mdx.remote.debug.handlers_")||[],KDa);g.kf(this.o);E7.fa.X.call(this)};
g.h.hc=function(a){j7("Controller",a)};
g.h.DE=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.RU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.NS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.gN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Eu,b))};
g.h.CE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.Ae(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.kf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.DE,this,this.o)),this.o.Kk(null));this.o.Pw(a)}}};
g.h.lY=function(){return this.o?this.o.aH():null};
g.h.qV=function(a){this.la()||(this.hc("Failed to estabilish a session: "+g.Fg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.VU=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.ZG=function(){this.la()||(this.B=hEa(this),F7("Updating custom receivers: "+g.Fg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.dX;E7.prototype.setConnectedScreenStatus=E7.prototype.cX;E7.prototype.stopSession=E7.prototype.mY;E7.prototype.getCastSession=E7.prototype.lY;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.kg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+U7(this):this.J};
g.h.clone=function(){return new S7(Y7(this))};g.C($7,g.GF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.VG=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Da(this.VG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Da(this.setVolume,a,b))};
g.h.UF=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Fg(b.style),g.ec(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Da(this.UF,a,b))};
g.h.Mx=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kb.id});var c=a8(this);c.audioTrackId=b.Kb.id;c8(this,c)}else b8(this,g.Da(this.Mx,a,b))};
g.h.UG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Da(this.UG,a,b))};
g.h.TG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Da(this.TG,a,b))};
g.h.Yz=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Yz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.fa.dispose.call(this)};
g.h.X=function(){uEa(this);this.C=null;this.D.clear();Z7(this,null);$7.fa.X.call(this)};
g.h.Nx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.xC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.MU=function(a,b){this.V(a,b)};
g.h.kS=function(a){if(!a)this.zn(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.zn=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),vEa(this),this.V("remotePlayerChange")};
g.h.jS=function(a){a?(vEa(this),this.V("remotePlayerChange")):this.zn(null)};
g.h.wS=function(){var a=rEa();a&&Z7(this,a)};
g.h.hc=function(a){j7("CP",a)};g.C(g8,g.GF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;V7(this.jb,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Fg(l));this.o.connect({method:"setPlaylist",
params:g.Fg(l)},a,QCa())}else h8("Connecting without params"),this.o.connect({},a,QCa());xEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.fa.dispose.call(this)};
g.h.X=function(){j8(this);l8(this);k8(this);g.ZD(this.J);this.J=window.NaN;g.ZD(this.K);this.K=window.NaN;this.B=null;g.qF(this.Y);this.Y.length=0;this.o.dispose();g8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.uL=function(){this.F(2)};
g.h.oS=function(){h8("Channel opened");this.O&&(this.O=!1,k8(this),this.N=g.XD((0,g.B)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
UCa(HDa(this.o),this.ca)};
g.h.lS=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.mS=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.nS=function(a){a.params?h8("Received: action="+a.action+", params="+g.Fg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.fx(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.Ia(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
AEa(this,a);break;case "loungeScreenDisconnected":g.Sa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
AEa(this,!1);break;case "remoteConnected":var b=new k6(g.fx(a.params.device));g.Ia(this.A,function(a){return b?a.id==b.id:!1})||g.Pa(this.A,b);
break;case "remoteDisconnected":b=new k6(g.fx(a.params.device));g.Sa(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":CEa(this,a);break;case "nowPlaying":EEa(this,a);break;case "onStateChange":DEa(this,a);break;case "onAdStateChange":FEa(this,a);break;case "onVolumeChanged":GEa(this,a);break;case "onSubtitlesTrackChanged":BEa(this,a);break;case "nowAutoplaying":HEa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":IEa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.OW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.ae;g8.prototype.ka=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ka;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();IDa(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ia=function(){var a=this.jb;this.B&&(a=this.jb.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ia;
g8.prototype.pa=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.ZD(this.J),this.J=g.XD((0,g.B)(this.OW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.o==b.o&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Fg(this.jb.A)==g.Fg(b.A)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.pa;g8.prototype.aa=function(){var a=this.o.F.id,b=g.Ia(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.aa;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ba;g8.prototype.ga=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.ga;g8.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.ku(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.xa;g8.prototype.ma=function(a,b){m8(this,a,b);zEa(this)};
g8.prototype.sendMessage=g8.prototype.ma;g.C(n8,n7);g.h=n8.prototype;g.h.Ae=function(a){return this.hd.$_gs(a)};
g.h.contains=function(a){return!!this.hd.$_c(a)};
g.h.get=function(a){return this.hd.$_g(a)};
g.h.start=function(){this.hd.$_st()};
g.h.add=function(a,b,c){this.hd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.hd.$_r(a,b,c)};
g.h.Er=function(a,b,c,d){this.hd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.hd.$_ubk(this.A[a]);this.A.length=0;this.hd=null;n8.fa.X.call(this)};
g.h.iY=function(){this.V("screenChange")};
g.h.lU=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.jY;w7.prototype.$_gsppc=w7.prototype.YG;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Er;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Ae;w7.prototype.$_gos=w7.prototype.XG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.ae;var o8=null,p8=null,E8=null,t8=[];g.r(F8,g.M);g.h=F8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.B.stop();this.C.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.zE,this);this.o.unsubscribe("remotePlayerChange",this.Cn,this);this.o.unsubscribe("remoteQueueChange",this.Eq,this);this.o.unsubscribe("autoplayUpNext",this.VD,this);this.o.unsubscribe("previousNextChange",this.wE,this);this.o.unsubscribe("nowAutoplaying",this.nE,this);this.o.unsubscribe("autoplayDismissed",this.UD,this);this.o=this.G=null};
g.h.SC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Cm(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Mx(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Mx(this.T.getVideoData(1).videoId,c)}};
g.h.iS=function(a){this.K.pL(a)};
g.h.JX=function(a){this.SC("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.jG=function(){var a=this.T.Ec("captions","track");g.Vb(a)||J8(this,a)};
g.h.kE=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.Cn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.Cn,this)}};
g.h.DT=function(){g.Vb(this.D)||UEa(this,this.D);this.F=!1};
g.h.zE=function(a,b){this.C.stop();2==b&&this.gG()};
g.h.Cn=function(){if(I8(this)){this.B.stop();var a=a8(this.o);switch(a.o){case 1081:case 1:H8(this,new g.CP(8));this.fG();break;case 1085:case 3:H8(this,new g.CP(9));break;case 1083:case 0:H8(this,new g.CP(2));this.J.stop();G8(this,this.T.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.CP(4));break;case 2:H8(this,new g.CP(4));G8(this,W7(a));break;case -1:H8(this,new g.CP(64));break;case -1E3:H8(this,new g.CP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
a8(this.o).A;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,UEa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.FG()}else TEa(this)};
g.h.wE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Eq=function(){I8(this)||TEa(this)};
g.h.uK=function(){this.o.Yz()};
g.h.VD=function(a){a&&(a=g.nE("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.RV,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.RV=function(a,b){var c=new g.sO(g.X(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.nE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.UD=function(){this.T.V("mdxautoplaycanceled")};
g.h.mQ=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.VG(a)};
g.h.FG=function(){if(I8(this)){var a=a8(this.o);this.A.Ga(this.O);a.muted?this.T.mute():this.T.tg();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.kE)}};
g.h.fG=function(){this.B.stop();if(!this.o.la()){var a=a8(this.o);a.rb()&&H8(this,new g.CP(8));G8(this,W7(a));this.B.start()}};
g.h.gG=function(){this.C.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.C.start()};g.r(L8,g.V);L8.prototype.D=function(a){WEa(this,a.state)};g.r(M8,g.CY);M8.prototype.K=function(){var a=this.T.Ec("remote","receivers");a&&1<a.length&&!this.T.Ec("remote","quickCast")?(this.H=g.gb(a,this.D,this),g.DY(this,(0,g.I)(a,this.D)),a=this.T.Ec("remote","currentReceiver"),this.Gf(this.D(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.D=function(a){return a.key};
M8.prototype.Ff=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
M8.prototype.Dd=function(a){g.CY.prototype.Dd.call(this,a);this.T.Ud("remote","currentReceiver",this.H[a]);this.C.Ob()};g.r(N8,g.FU);g.h=N8.prototype;g.h.create=function(){NEa(g.wM(g.X(this.o)));this.F.push(g.SF("yt-remote-before-disconnect",this.eS,this));this.F.push(g.SF("yt-remote-connection-change",this.WU,this));this.F.push(g.SF("yt-remote-receiver-availability-change",this.xE,this));this.F.push(g.SF("yt-remote-auto-connect",this.UU,this));this.F.push(g.SF("yt-remote-receiver-resumed",this.TU,this));this.xE()};
g.h.load=function(){this.o.zv();g.FU.prototype.load.call(this);this.D=new F8(this,this.o,this.A);var a=(a=SEa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));VEa(this,this.G,this.G);g.N_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.lf(this.D,this.A);this.A=this.D=null;g.FU.prototype.unload.call(this);g.N_(this.o.app,5)};
g.h.X=function(){g.TF(this.F);g.FU.prototype.X.call(this)};
g.h.ln=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.SC.apply(this.D,[a].concat(g.oa(c)))};
g.h.kL=function(){return this.loaded?this.D.suggestion:null};
g.h.kg=function(){return this.A?a8(this.A).kg:!1};
g.h.hasNext=function(){return this.A?a8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.aQ=function(){var a=a8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.kd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.bQ=function(){this.A&&this.A.TG()};
g.h.cQ=function(){this.A&&this.A.UG()};
g.h.eS=function(a){1==a&&(this.K=this.A?a8(this.A):null)};
g.h.WU=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.kf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.wC(a.videoId,W7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.xE=function(){this.H=[this.B].concat(PEa());var a=z8()||this.B;O8(this,a);this.o.ya("onMdxReceiversChange")};
g.h.UU=function(){var a=z8();O8(this,a)};
g.h.TU=function(){this.C=z8()};
g.h.ZP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.dQ=function(){e8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Mc=function(){return!1};g.BX.remote=N8;})(_yt_player);
